{{- if .Values.createClusterRoles -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crownlabs-view-instances
  labels:
    {{- include "crownlabs.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - crownlabs.polito.it
    resources:
      - instances
      - instances/status
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crownlabs-manage-instances
  labels:
    {{- include "crownlabs.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - crownlabs.polito.it
    resources:
      - instances
      - instances/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
      
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crownlabs-view-instancesnapshots
  labels:
    {{- include "crownlabs.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - crownlabs.polito.it
    resources:
      - instancesnapshots
      - instancesnapshots/status
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crownlabs-manage-instancesnapshots
  labels:
    {{- include "crownlabs.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - crownlabs.polito.it
    resources:
      - instancesnapshots
      - instancesnapshots/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crownlabs-view-templates
  labels:
    {{- include "crownlabs.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - crownlabs.polito.it
    resources:
      - templates
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crownlabs-manage-templates
  labels:
    {{- include "crownlabs.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - crownlabs.polito.it
    resources:
      - templates
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crownlabs-view-tenants
  labels:
    {{- include "crownlabs.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - crownlabs.polito.it
    resources:
      - tenants
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crownlabs-manage-tenants
  labels:
    {{- include "crownlabs.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - crownlabs.polito.it
    resources:
      - tenants
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crownlabs-view-workspaces
  labels:
    {{- include "crownlabs.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - crownlabs.polito.it
    resources:
      - workspaces
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crownlabs-manage-workspaces
  labels:
    {{- include "crownlabs.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - crownlabs.polito.it
    resources:
      - workspaces
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crownlabs-view-image-lists
  labels:
    {{- include "crownlabs.labels" . | nindent 4 }}
rules:
- apiGroups:
  - crownlabs.polito.it
  resources:
  - imagelists
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crownlabs-manage-image-lists
  labels:
    {{- include "crownlabs.labels" . | nindent 4 }}
rules:
- apiGroups:
  - crownlabs.polito.it
  resources:
  - imagelists
  verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
    - deletecollection
{{- end }}
