apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbacResourcesName }}
  labels:
    {{- include "instance-operator.labels" . | nindent 4 }}
rules:
- apiGroups: ["crownlabs.polito.it"]
  resources: ["instances", "instances/status", "instancesnapshots", "instancesnapshots/status"]
  verbs: ["get","list","watch","create","update","patch","delete", "deleteCollection"]

- apiGroups: ["crownlabs.polito.it"]
  resources: ["templates", "tenants"]
  verbs: ["get","list","watch"]

- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get","list","watch"]

- apiGroups: [""]
  resources: ["secrets","services","events"]
  verbs: ["get","list","watch","create","patch","update"]

- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","list","watch","create","patch","update"]

- apiGroups: ["batch", "extensions"]
  resources: ["jobs", "jobs/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","list","watch","create","patch","update"]

- apiGroups: ["kubevirt.io"]
  resources: ["virtualmachines", "virtualmachineinstances"]
  verbs: ["get","list","watch","create","patch","update"]

- apiGroups: ["cdi.kubevirt.io"]
  resources: ["datavolumes"]
  verbs: ["get","list","watch","create", "patch", "update"]

- apiGroups: ["cdi.kubevirt.io"]
  resources: ["datavolumes/source"]
  verbs: ["create", "patch", "update"]