apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "instance-operator.fullname" . }}
  labels:
    {{- include "instance-operator.labels" . | nindent 4 }}
{{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "instance-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "instance-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "instance-operator.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "instance-operator.version" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/bin/controller
          args:
            - "--webdav-secret-name={{ .Values.configurations.nextcloud.webdavSecretName }}"
            - "--namespace-whitelist={{ .Values.configurations.generic.whitelistLabels }}"
            - "--website-base-url={{ .Values.configurations.generic.websiteBaseUri }}"
            - "--nextcloud-base-url={{ .Values.configurations.nextcloud.baseUrl }}"
            - "--oauth2-proxy-image={{ .Values.configurations.generic.oauth2ProxyImage }}"
            - "--oidc-client-secret={{ .Values.configurations.oidc.clientSecret }}"
            - "--oidc-provider-url={{ .Values.configurations.oidc.providerUrl }}"
            - "--container-env-sidecars-tag={{ include "instance-operator.containerEnvironmentSidecarsTag" . }}"
            - "--container-env-vnc-img={{ .Values.configurations.containerEnvironmentOptions.vncImage }}"
            - "--container-env-websockify-img={{ .Values.configurations.containerEnvironmentOptions.websockifyImage }}"
            - "--container-env-novnc-img={{ .Values.configurations.containerEnvironmentOptions.novncImage }}"
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: probes
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: probes
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: probes
            initialDelaySeconds: 3
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  {{- include "instance-operator.selectorLabels" . | nindent 18 }}
              topologyKey: kubernetes.io/hostname
