# Default values for crownlabs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  version: ""

createClusterRoles: true

dashboard:
  replicaCount: 1
  image:
    repository: crownlabs/frontend
  ingress:
    hostname: https://crownlabs.example.com
  configurations:
    oidc:
      clientId: k8s
      clientSecret: <client-secret>
      providerUrl: https://auth.example.com/auth/realms/crownlabs

instance-operator:
  replicaCount: 1
  image:
    repository: crownlabs/instance-operator
  rbacResourcesName: crownlabs-instance-operator
  configurations:
    generic:
      oauth2ProxyImage: quay.io/oauth2-proxy/oauth2-proxy
      whitelistLabels: crownlabs.polito.it/operator-selector=production
      websiteBaseUri: crownlabs.example.com
    nextcloud:
      baseUrl: https://nextcloud.example.com
      webdavSecretName: nextcloud-credentials
    oidc:
      clientId: k8s
      clientSecret: <client-secret>
      providerUrl: https://auth.example.com/auth/realms/crownlabs
    containerEnvironmentOptions:
      tag: ""
      vncImage: crownlabs/tigervnc
      websockifyImage: crownlabs/websockify
      novncImage: crownlabs/novnc

tenant-operator:
  replicaCount: 1
  image:
    repository: crownlabs/tenant-operator
  rbacResourcesName: crownlabs-tenant-operator
  configurations:
    targetLabel: crownlabs.polito.it/operator-selector=production
    keycloak:
      url: "https://auth.crownlabs.example.com/"
      loginRealm: master
      targetRealm: crownlabs
      targetClient: k8s
      user: username
      pass: password
    nextcloud:
      url: "https://nextcloud.crownlabs.example.com/"
      user: username
      pass: password

bastion-operator:
  replicaCount: 1
  image:
    repositoryBastion: crownlabs/ssh-bastion
    repositorySidecar: crownlabs/bastion-operator
  rbacResourcesName: crownlabs-bastion-operator
  serviceAnnotations: {}

image-list:
  replicaCount: 1
  image:
    repository: crownlabs/crownlabs-image-list
  rbacResourcesName: crownlabs-image-list
  configurations:
    registryUrl: http://docker-registry.docker-registry:5000
    advRegistryName: registry.crownlabs.example.com
    imageListName: crownlabs-virtual-machine-images
    updateInterval: 60

delete-stale-instances:
  image:
    repository: crownlabs/delete-stale-instances
  rbacResourcesName: crownlabs-delete-stale-instances
  configurations:
    dryRun: true
    schedule: "*/15 * * * *"
